name: Windows

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: [master, dev, experiment, refactor]
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    branches: [master, dev, experiment, refactor]
    
env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ${{github.workspace}}/.local
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build:
    
    name: ${{ matrix.config.os }}-${{ matrix.config.compiler }}-${{ matrix.config.version }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            compiler: MSVC
            cc: cl
            cxx: cl
            version: "2019"

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{env.INSTALL_LOCATION}}
        key: ${{runner.os}}-dependencies

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Set system environment variables
      if: matrix.config.os == 'windows-latest'
      run: .github/workflows/winenv.bat

    - name: Install Bass
      run: |
        cd thirdparty
        git clone https://github.com/filoper/bass24.git

    - name: Install GoogleTest
      run: |
        cd thirdparty
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd googletest
        cmake -Bbuild -GNinja -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_INSTALL_PREFIX="$env:INSTALL_LOCATION" -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE" -Dgtest_force_shared_crt=1
        cmake --build build --config "$env:BUILD_TYPE"
        cmake --build build --target install --config "$env:BUILD_TYPE"

    - name: Configure
      run: cmake -Bbuild -GNinja -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -DCMAKE_PREFIX_PATH="$env:INSTALL_LOCATION" -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE" -DCMAKE_INSTALL_PREFIX="$env:INSTALL_LOCATION" -DENABLE_CODE_COVERAGE=1

    - name: Build
      run: | 
        cmake --build build --config "$env:BUILD_TYPE"
        cmake --install build --config "$env:BUILD_TYPE"
    
    - name: Run tests
      run: |
        cd build
        ctest -C $BUILD_TYPE -VV

    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      with:
        name: msclient-win
        path: |
          ${{github.workspace}}/installed/bin/
